### ISSUE TITLE
Error while training pruned_transducer_stateless2

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/icefall#603]
While training, I am getting the following error. If I re-start the training from an earlier checkpoint, it proceeds to several next checkpoints before stopping like this again. The purpose of saving the batch I think is for debugging purposes, but I am not sure what to look for at this stage. Please advise. The recipe is adapted from librispeech for 8K data.

2022-10-05 23:42:56,919 INFO [train.py:814] (3/4) Epoch 0, batch 25600, loss[loss=0.2133, simple_loss=0.2315, pruned_loss=0.09752, over 4663.00 frames. utt_duration=3110 frames, utt_pad_proportion=0.009079, over 6.00 utterances.], tot_loss[loss=0.312, simple_loss=0.33, pruned_loss=0.1471, over 932672.09 frames. utt_duration=1056 frames, utt_pad_proportion=0.06028, over 3537.38 utterances.], batch size: 6, lr: 1.09e-03
2022-10-05 23:43:02,341 INFO [utils.py:968] (1/4) Saving batch to pruned_transducer_stateless2/exp_multi/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt
2022-10-05 23:43:02,391 INFO [utils.py:974] (1/4) features shape: torch.Size([202, 131, 80])
2022-10-05 23:43:02,392 INFO [utils.py:978] (1/4) num tokens: 564
Traceback (most recent call last):
  File "/mnt/dsk1/icefall/egs/8k/./pruned_transducer_stateless2/train.py", line 1089, in <module>
    main()
  File "/mnt/dsk1/icefall/egs/8k/./pruned_transducer_stateless2/train.py", line 1080, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/dsk1/icefall/egs/8k/pruned_transducer_stateless2/train.py", line 994, in run
    train_one_epoch(
  File "/mnt/dsk1/icefall/egs/8k/pruned_transducer_stateless2/train.py", line 766, in train_one_epoch
    loss, loss_info = compute_loss(
  File "/mnt/dsk1/icefall/egs/8k/pruned_transducer_stateless2/train.py", line 601, in compute_loss
    simple_loss, pruned_loss = model(
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 929, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/dsk1/icefall/egs/8k/pruned_transducer_stateless2/model.py", line 158, in forward
    simple_loss, (px_grad, py_grad) = k2.rnnt_loss_smoothed(
  File "/home/ngoel/k2/k2/python/k2/rnnt_loss.py", line 1308, in rnnt_loss_smoothed
    px, py = get_rnnt_logprobs_smoothed(
  File "/home/ngoel/k2/k2/python/k2/rnnt_loss.py", line 1127, in get_rnnt_logprobs_smoothed
    assert T >= S
AssertionError

**Comment by csukuangfj** [comment]
Can you print out the value of T and S on assert failure.

Also, please check that you are using the latest k2.


You get the assertion error because you have too many tokens in your utterance but with too few feature frames.

**Comment by csukuangfj** [comment]
You can use torch.load()


That pt file is saved by torch.save()

**Comment by danpovey** [comment]
We should change our scripts to check this at an earlier point and just skip the batch, so that it doesn't kill entire runs.

**Comment by ngoel17** [comment]
I would at least throw a warning instead of a silent skip because it could help someone fix their bad data.

**Comment by csukuangfj** [comment]
> We should change our scripts to check this at an earlier point and just skip the batch, so that it doesn't kill entire runs.

Please see https://github.com/k2-fsa/icefall/pull/604

**Comment by ngoel17** [comment]
Thanks. It would be awesome if it could be part of the recipe "Before" feature extraction, and not part of train or dataloader. For one, like I try to mix multiple datasets that have different size and different ratio, so only iterations exist in my dataloader and not an epoch. Second, we rent the GPUs and any data preparation related issues are better discovered before the GPU training begins.

**Comment by csukuangfj** [comment]
> Thanks. It would be awesome if it could be part of the recipe "Before" feature extraction, and not part of train or dataloader. For one, like I try to mix multiple datasets that have different size and different ratio, so only iterations exist in my dataloader and not an epoch. Second, we rent the GPUs and any data preparation related issues are better discovered before the GPU training begins.

@ngoel17 

I have updated that [PR](https://github.com/k2-fsa/icefall/pull/604) to provide a standalone script so that you can filter your cutset offline.

Could you re-try to see whether it fixes your issue?

(Hint: You can find the usage in `./local/compute_fbank_librispeech.py`)

**Comment by ngoel17** [comment]
resolved

**Comment by csukuangfj** [comment]
Thanks for testing.

**Comment by desh2608** [comment]
@csukuangfj 

I am training a Zipformer model on AMI. I applied the following filter on the training cuts:
```python
        def _remove_short_and_long_utt(c: Cut):
            if c.duration < 0.1 or c.duration > 25.0:
                return False

            # In pruned RNN-T, we require that T >= S
            # where T is the number of feature frames after subsampling
            # and S is the number of tokens in the utterance

            # In ./zipformer.py, the conv module uses the following expression
            # for subsampling
            T = (c.num_frames - 7) // 2
            tokens = sp.encode(c.supervisions[0].text, out_type=str)
            return T >= len(tokens)
```

However, I still get the assertion error during training:
```python
2022-11-14 22:54:39,101 INFO [train.py:1129] (2/4) features shape: torch.Size([285, 42, 80])
2022-11-14 22:54:39,102 INFO [train.py:1133] (2/4) num tokens: 423
Traceback (most recent call last):
  File "pruned_transducer_stateless7/train.py", line 1196, in <module>
    main()
  File "pruned_transducer_stateless7/train.py", line 1187, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/exp/draj/mini_scale_2022/icefall/egs/ami/ASR/pruned_transducer_stateless7/train.py", line 1067, in run
    train_one_epoch(
  File "/exp/draj/mini_scale_2022/icefall/egs/ami/ASR/pruned_transducer_stateless7/train.py", line 797, in train_one_epoch
    loss, loss_info = compute_loss(
  File "/exp/draj/mini_scale_2022/icefall/egs/ami/ASR/pruned_transducer_stateless7/train.py", line 662, in compute_loss
    simple_loss, pruned_loss = model(
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/exp/draj/mini_scale_2022/icefall/egs/ami/ASR/pruned_transducer_stateless7/model.py", line 150, in forward
    simple_loss, (px_grad, py_grad) = k2.rnnt_loss_smoothed(
  File "/exp/draj/mini_scale_2022/k2/k2/python/k2/rnnt_loss.py", line 1516, in rnnt_loss_smoothed
    px, py = get_rnnt_logprobs_smoothed(
  File "/exp/draj/mini_scale_2022/k2/k2/python/k2/rnnt_loss.py", line 1316, in get_rnnt_logprobs_smoothed
    assert T >= S, (T, S)
AssertionError: (9, 10)
```

I inspected the erroneous batch and verified that if I use the formula `T=(num_frames - 7)//2`, then T>=S is not violated for any item in the batch. Perhaps then this is not the correct equation for subsampling factor in the Zipformer?

**Comment by csukuangfj** [comment]
> 2022-11-14 22:54:39,101 INFO [train.py:1129] (2/4) features shape: torch.Size([285, 42, 80])

What is the output of the encoder network?

---

> I inspected the erroneous batch and verified that if I use the formula T=(num_frames - 7)//2

No, it is correct. We have unit tests for that.
https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L1839-L1848

**Comment by desh2608** [comment]
> > 2022-11-14 22:54:39,101 INFO [train.py:1129] (2/4) features shape: torch.Size([285, 42, 80])
> 
> What is the output of the encoder network?
> 

torch.Size([285, 9, 384])

**Comment by desh2608** [comment]
I stepped through the `forward()` function of the zipformer, and here are some observations:
* At the input to the zipformer, the shape is `[285, 42, 80]` as expected.
* After the `encoder_embed` ([this line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L263)), the shape becomes `[285, 17, 384]`. This is again expected due to the `Conv2DSubsampling`.
* After passing this through the zipformer layers, the shape is `[17, 285, 384]` (there is a permute that happens before the layers so this is fine).
* [This line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L288) further subsamples the output to shape `[9, 285, 384]`, since the Zipformer is initialized with `output_downsampling_factor=2`. Why is this extra downsampling needed?

**Comment by desh2608** [comment]
> I stepped through the `forward()` function of the zipformer, and here are some observations:
> 
> * At the input to the zipformer, the shape is `[285, 42, 80]` as expected.
> * After the `encoder_embed` ([this line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L263)), the shape becomes `[285, 17, 384]`. This is again expected due to the `Conv2DSubsampling`.
> * After passing this through the zipformer layers, the shape is `[17, 285, 384]` (there is a permute that happens before the layers so this is fine).
> * [This line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L288) further subsamples the output to shape `[9, 285, 384]`, since the Zipformer is initialized with `output_downsampling_factor=2`. Why is this extra downsampling needed?

Following up on this, if I use the following formula to filter out cuts, I can train successfully: 
`T = ((num_frames - 7)//2 + 1)//2`.

**Comment by csukuangfj** [comment]
> > I stepped through the `forward()` function of the zipformer, and here are some observations:
> 
> > 
> 
> > * At the input to the zipformer, the shape is `[285, 42, 80]` as expected.
> 
> > * After the `encoder_embed` ([this line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L263)), the shape becomes `[285, 17, 384]`. This is again expected due to the `Conv2DSubsampling`.
> 
> > * After passing this through the zipformer layers, the shape is `[17, 285, 384]` (there is a permute that happens before the layers so this is fine).
> 
> > * [This line](https://github.com/k2-fsa/icefall/blob/855c76655b49de61a5c6d054a7ff2158a639e6f7/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L288) further subsamples the output to shape `[9, 285, 384]`, since the Zipformer is initialized with `output_downsampling_factor=2`. Why is this extra downsampling needed?
> 
> 
> 
> Following up on this, if I use the following formula to filter out cuts, I can train successfully: 
> 
> `T = ((num_frames - 7)//2 + 1)//2`.

Thanks! Could you please make a PR to fix it?

**Comment by groovemaxRong** [comment]
i met this error again when using BlankSkip in pruned_transducer_stateless7_ctc_bs, and is okay when not using BlankSkip in pruned_transducer_stateless7_ctc

![image](https://user-images.githubusercontent.com/13691793/209540780-bc127a12-7df8-46c6-a447-834750c9481c.png)

**Comment by yfyeung** [comment]
> i met this error again when using BlankSkip in pruned_transducer_stateless7_ctc_bs, and is okay when not using BlankSkip in pruned_transducer_stateless7_ctc
> 
> ![image](https://user-images.githubusercontent.com/13691793/209540916-e77abe06-af41-4571-9c8c-b10f6c30e5ce.png)

Using blank skip may result in a situation where T is shorter than S. You may consider deleting this short audio segment. 
Essentially, it's a question of whether this assert statement is necessary.
